
########################################################################
########################################################################
#
#       Faustservice (remote Faust compiler) in a docker
#                 (L. Champenois & Y. Orlarey)
#
########################################################################
########################################################################

FROM grame/faust-ready-ubuntu1604

########################################################################
# Now we can clone and compile all the Faust related git repositories
########################################################################

RUN echo "CHANGE THIS NUMBER TO FORCE REGENERATION : 002"

# faustservice first as it changes less often
RUN git clone -n https://github.com/grame-cncm/faustservice.git; \
git -C faustservice checkout 5774a276e2eff65300424d1036415773272c7732; \
make -C faustservice

# then the faust compiler itself
RUN git clone -n https://github.com/grame-cncm/faust.git; \
git -C faust checkout 6330557c5dc13c7c9fbf2ad352c15b64aaa454ef; \
make -C faust; \
make -C faust install

########################################################################
# And starts Faustservice
########################################################################
ENV GRADLE_USER_HOME=/tmp/gradle
EXPOSE 8080
WORKDIR /faustservice
CMD ./faustweb --port 8080 --sessions-dir /tmp/sessions

