
########################################################################
########################################################################
#
#       Faustservice (remote Faust compiler) in a docker
#                 (L. Champenois & Y. Orlarey)
#
########################################################################
########################################################################

FROM faust-ready-ubuntu:1604

########################################################################
# Now we can clone and compile all the Faust related git repositories
########################################################################

# Force regeneration
RUN ls -a
RUN ls -a

# faustservice first as it changes less often
RUN git clone https://github.com/grame-cncm/faustservice.git; \
git -C faustservice checkout server; \
make -C faustservice

# then the faust compiler itself
RUN git clone https://github.com/grame-cncm/faust.git; \
git -C faust checkout faust-server; \
make -C faust; \
make -C faust install

########################################################################
# And starts Faustservice
########################################################################
ENV GRADLE_USER_HOME=/tmp/gradle
EXPOSE 8080
WORKDIR /faustservice
CMD ./faustweb --port 8080 --sessions-dir /tmp/sessions

