
########################################################################
########################################################################
#
#       Faustservice (remote Faust compiler) in a docker
#                 (L. Champenois & Y. Orlarey)
#
########################################################################
########################################################################

FROM grame/faustready-ubuntu-1604:002

########################################################################
# Now we can clone and compile all the Faust related git repositories
########################################################################

RUN echo "CHANGE THIS NUMBER TO FORCE REGENERATION : 002"

# faustservice first as it changes less often
RUN git clone -n https://github.com/grame-cncm/faustservice.git; \
git -C faustservice checkout server; \
make -C faustservice

# then the faust compiler itself
RUN git clone -n https://github.com/grame-cncm/faust.git; \
git -C faust checkout master-dev; \
make -C faust; \
make -C faust install


########################################################################
# Force Gradle upgrade
########################################################################
ENV GRADLE_USER_HOME=/tmp/gradle

RUN echo "process=+;" > tmp.dsp; \
faust2android tmp.dsp; \
faust2smartkeyb -android tmp.dsp; \
rm tmp.apk


########################################################################
# And starts Faustservice
########################################################################
EXPOSE 8080
WORKDIR /faustservice
### CMD ./faustweb --port 8080 --sessions-dir /tmp/sessions

